-- customs.lua
Customs = {}

-- Vehicle catalog for the warehouse.
-- Used when Config.VehicleSource = 'custom' (required for ESX, optional for QB/QBox).
-- Fields: name (display), model (spawn name), price (base), brand (manufacturer)

Customs.VehicleModels = {
    -- Compacts
    { name = 'Blista',           model = 'blista',       price = 15000,   brand = 'Dinka' },
    { name = 'Brioso R/A',       model = 'brioso',       price = 18000,   brand = 'Grotti' },
    { name = 'Issi',             model = 'issi2',        price = 12000,   brand = 'Weeny' },
    { name = 'Panto',            model = 'panto',        price = 10000,   brand = 'Benefactor' },
    { name = 'Prairie',          model = 'prairie',      price = 14000,   brand = 'Bollokan' },
    { name = 'Rhapsody',         model = 'rhapsody',     price = 11000,   brand = 'Declasse' },
    -- Coupes
    { name = 'Exemplar',         model = 'exemplar',     price = 42000,   brand = 'Dewbauchee' },
    { name = 'F620',             model = 'f620',         price = 38000,   brand = 'Ocelot' },
    { name = 'Felon',            model = 'felon',        price = 35000,   brand = 'Lampadati' },
    { name = 'Jackal',           model = 'jackal',       price = 40000,   brand = 'Ocelot' },
    { name = 'Oracle',           model = 'oracle',       price = 45000,   brand = 'Ubermacht' },
    { name = 'Sentinel',         model = 'sentinel',     price = 36000,   brand = 'Ubermacht' },
    { name = 'Windsor',          model = 'windsor',      price = 70000,   brand = 'Enus' },
    { name = 'Zion',             model = 'zion',         price = 32000,   brand = 'Ubermacht' },
    -- Sedans
    { name = 'Asea',             model = 'asea',         price = 8000,    brand = 'Declasse' },
    { name = 'Asterope',         model = 'asterope',     price = 9000,    brand = 'Karin' },
    { name = 'Fugitive',         model = 'fugitive',     price = 22000,   brand = 'Cheval' },
    { name = 'Glendale',         model = 'glendale',     price = 12000,   brand = 'Benefactor' },
    { name = 'Ingot',            model = 'ingot',        price = 7000,    brand = 'Vulcar' },
    { name = 'Intruder',         model = 'intruder',     price = 16000,   brand = 'Karin' },
    { name = 'Premier',          model = 'premier',      price = 10000,   brand = 'Declasse' },
    { name = 'Schafter',         model = 'schafter2',    price = 55000,   brand = 'Benefactor' },
    { name = 'Stanier',          model = 'stanier',      price = 8000,    brand = 'Vapid' },
    { name = 'Stratum',          model = 'stratum',      price = 9500,    brand = 'Zirconium' },
    { name = 'Sultan',           model = 'sultan',       price = 18000,   brand = 'Karin' },
    { name = 'Tailgater',        model = 'tailgater',    price = 28000,   brand = 'Obey' },
    { name = 'Warrener',         model = 'warrener',     price = 11000,   brand = 'Vulcar' },
    { name = 'Washington',       model = 'washington',   price = 15000,   brand = 'Albany' },
    -- Sports
    { name = 'Alpha',            model = 'alpha',        price = 95000,   brand = 'Albany' },
    { name = 'Banshee',          model = 'banshee',      price = 85000,   brand = 'Bravado' },
    { name = 'Buffalo',          model = 'buffalo',      price = 35000,   brand = 'Bravado' },
    { name = 'Buffalo S',        model = 'buffalo2',     price = 45000,   brand = 'Bravado' },
    { name = 'Carbonizzare',     model = 'carbonizzare', price = 120000,  brand = 'Grotti' },
    { name = 'Comet',            model = 'comet2',       price = 110000,  brand = 'Pfister' },
    { name = 'Coquette',         model = 'coquette',     price = 130000,  brand = 'Invetero' },
    { name = 'Elegy RH8',        model = 'elegy2',       price = 95000,   brand = 'Annis' },
    { name = 'Feltzer',          model = 'feltzer2',     price = 115000,  brand = 'Benefactor' },
    { name = 'Fusilade',         model = 'fusilade',     price = 55000,   brand = 'Schyster' },
    { name = 'Futo',             model = 'futo',         price = 12000,   brand = 'Karin' },
    { name = 'Jester',           model = 'jester',       price = 140000,  brand = 'Dinka' },
    { name = 'Massacro',         model = 'massacro',     price = 155000,  brand = 'Dewbauchee' },
    { name = 'Penumbra',         model = 'penumbra',     price = 24000,   brand = 'Maibatsu' },
    { name = 'Rapid GT',         model = 'rapidgt',      price = 90000,   brand = 'Dewbauchee' },
    { name = 'Schwartzer',       model = 'schwarzer',    price = 60000,   brand = 'Benefactor' },
    { name = 'Sultan RS',        model = 'sultanrs',     price = 175000,  brand = 'Karin' },
    -- Sports Classics
    { name = 'Coquette Classic', model = 'coquette2',    price = 250000,  brand = 'Invetero' },
    { name = 'JB 700',           model = 'jb700',        price = 350000,  brand = 'Dewbauchee' },
    { name = 'Manana',           model = 'manana',       price = 8000,    brand = 'Albany' },
    { name = 'Monroe',           model = 'monroe',       price = 280000,  brand = 'Pegassi' },
    { name = 'Pigalle',          model = 'pigalle',      price = 160000,  brand = 'Lampadati' },
    { name = 'Roosevelt',        model = 'btype',        price = 450000,  brand = 'Albany' },
    { name = 'Stinger GT',       model = 'stingergt',    price = 320000,  brand = 'Grotti' },
    { name = 'Tornado',          model = 'tornado',      price = 15000,   brand = 'Declasse' },
    { name = 'Z-Type',           model = 'ztype',        price = 950000,  brand = 'Truffade' },
    -- Super
    { name = 'Adder',            model = 'adder',        price = 1000000, brand = 'Truffade' },
    { name = 'Bullet',           model = 'bullet',       price = 120000,  brand = 'Vapid' },
    { name = 'Cheetah',          model = 'cheetah',      price = 650000,  brand = 'Grotti' },
    { name = 'Entity XF',        model = 'entityxf',     price = 795000,  brand = 'Overflod' },
    { name = 'Infernus',         model = 'infernus',     price = 440000,  brand = 'Pegassi' },
    { name = 'Osiris',           model = 'osiris',       price = 950000,  brand = 'Pegassi' },
    { name = 'T20',              model = 't20',          price = 2200000, brand = 'Progen' },
    { name = 'Turismo R',        model = 'turismor',     price = 500000,  brand = 'Grotti' },
    { name = 'Vacca',            model = 'vacca',        price = 240000,  brand = 'Pegassi' },
    { name = 'Voltic',           model = 'voltic',       price = 150000,  brand = 'Coil' },
    { name = 'Zentorno',         model = 'zentorno',     price = 725000,  brand = 'Pegassi' },
    -- Muscle
    { name = 'Blade',            model = 'blade',        price = 16000,   brand = 'Vapid' },
    { name = 'Buccaneer',        model = 'buccaneer',    price = 18000,   brand = 'Albany' },
    { name = 'Dominator',        model = 'dominator',    price = 35000,   brand = 'Vapid' },
    { name = 'Dukes',            model = 'dukes',        price = 28000,   brand = 'Imponte' },
    { name = 'Gauntlet',         model = 'gauntlet',     price = 32000,   brand = 'Bravado' },
    { name = 'Hotknife',         model = 'hotknife',     price = 90000,   brand = 'Vapid' },
    { name = 'Phoenix',          model = 'phoenix',      price = 15000,   brand = 'Imponte' },
    { name = 'Picador',          model = 'picador',      price = 10000,   brand = 'Cheval' },
    { name = 'Ruiner',           model = 'ruiner',       price = 12000,   brand = 'Imponte' },
    { name = 'Sabre Turbo',      model = 'sabregt',      price = 20000,   brand = 'Declasse' },
    { name = 'Vigero',           model = 'vigero',       price = 14000,   brand = 'Declasse' },
    { name = 'Virgo',            model = 'virgo',        price = 16000,   brand = 'Albany' },
    -- SUVs
    { name = 'Baller',           model = 'baller',       price = 55000,   brand = 'Gallivanter' },
    { name = 'Cavalcade',        model = 'cavalcade',    price = 45000,   brand = 'Albany' },
    { name = 'Dubsta',           model = 'dubsta',       price = 50000,   brand = 'Benefactor' },
    { name = 'FQ 2',             model = 'fq2',          price = 28000,   brand = 'Fathom' },
    { name = 'Granger',          model = 'granger',      price = 35000,   brand = 'Declasse' },
    { name = 'Gresley',          model = 'gresley',      price = 32000,   brand = 'Bravado' },
    { name = 'Habanero',         model = 'habanero',     price = 22000,   brand = 'Emperor' },
    { name = 'Huntley S',        model = 'huntley',      price = 65000,   brand = 'Enus' },
    { name = 'Landstalker',      model = 'landstalker',  price = 38000,   brand = 'Dundreary' },
    { name = 'Mesa',             model = 'mesa',         price = 28000,   brand = 'Canis' },
    { name = 'Patriot',          model = 'patriot',      price = 40000,   brand = 'Mammoth' },
    { name = 'Radius',           model = 'radi',         price = 24000,   brand = 'Vapid' },
    { name = 'Rocoto',           model = 'rocoto',       price = 42000,   brand = 'Obey' },
    { name = 'Seminole',         model = 'seminole',     price = 20000,   brand = 'Canis' },
    { name = 'XLS',              model = 'xls',          price = 48000,   brand = 'Benefactor' },
    -- Off-Road
    { name = 'BF Injection',     model = 'bfinjection',  price = 16000,   brand = 'BF' },
    { name = 'Bifta',            model = 'bifta',        price = 12000,   brand = 'BF' },
    { name = 'Blazer',           model = 'blazer',       price = 8000,    brand = 'Nagasaki' },
    { name = 'Bodhi',            model = 'bodhi2',       price = 6000,    brand = 'Canis' },
    { name = 'Dubsta 6x6',       model = 'dubsta3',      price = 120000,  brand = 'Benefactor' },
    { name = 'Kamacho',          model = 'kamacho',      price = 45000,   brand = 'Canis' },
    { name = 'Rebel',            model = 'rebel2',       price = 15000,   brand = 'Karin' },
    { name = 'Sandking',         model = 'sandking',     price = 38000,   brand = 'Vapid' },
    -- Vans
    { name = 'Bison',            model = 'bison',        price = 18000,   brand = 'Bravado' },
    { name = 'Bobcat XL',        model = 'bobcatxl',     price = 16000,   brand = 'Vapid' },
    { name = 'Minivan',          model = 'minivan',      price = 14000,   brand = 'Vapid' },
    { name = 'Rumpo',            model = 'rumpo',        price = 12000,   brand = 'Bravado' },
    { name = 'Speedo',           model = 'speedo',       price = 10000,   brand = 'Vapid' },
    { name = 'Surfer',           model = 'surfer',       price = 8000,    brand = 'BF' },
    { name = 'Youga',            model = 'youga',        price = 11000,   brand = 'Bravado' },
    -- Motorcycles
    { name = 'Akuma',            model = 'akuma',        price = 15000,   brand = 'Dinka' },
    { name = 'Bagger',           model = 'bagger',       price = 18000,   brand = 'Western' },
    { name = 'Bati 801',         model = 'bati',         price = 22000,   brand = 'Pegassi' },
    { name = 'Carbon RS',        model = 'carbonrs',     price = 28000,   brand = 'Nagasaki' },
    { name = 'Double T',         model = 'double',       price = 20000,   brand = 'Dinka' },
    { name = 'Enduro',           model = 'enduro',       price = 8000,    brand = 'Dinka' },
    { name = 'Faggio',           model = 'faggio',       price = 3000,    brand = 'Pegassi' },
    { name = 'Hakuchou',         model = 'hakuchou',     price = 35000,   brand = 'Shitzu' },
    { name = 'Hexer',            model = 'hexer',        price = 14000,   brand = 'LCC' },
    { name = 'Innovation',       model = 'innovation',   price = 25000,   brand = 'Western' },
    { name = 'Nemesis',          model = 'nemesis',      price = 12000,   brand = 'Principe' },
    { name = 'PCJ-600',          model = 'pcj',          price = 10000,   brand = 'Shitzu' },
    { name = 'Ruffian',          model = 'ruffian',      price = 9000,    brand = 'Pegassi' },
    { name = 'Sanchez',          model = 'sanchez',      price = 7000,    brand = 'Maibatsu' },
    { name = 'Thrust',           model = 'thrust',       price = 40000,   brand = 'Dinka' },
    { name = 'Vader',            model = 'vader',        price = 8500,    brand = 'Shitzu' },
}